# Site Settings
title: Aquacise
email: aquaciseswimming@gmail.com
description: >
  Aquacise Lessons !
# Project site: https://originaldogmeat.github.io/aquacise-new/
baseurl: "/aquacise-new"
url: "https://originaldogmeat.github.io"
twitter_username: 
github_username:  originaldogmeat
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
  parse_block_html: true
  booking:
  supabase_url: "https://zptjctewgzktagkdcugi.supabase.co"
  supabase_anon_key: "sb_publishable_otImHsT1ehrx1kB916a2dw_YIx42awY"
